language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

gemfile:
  - gemfiles/Rails_5.0.x.gemfile
  - gemfiles/Rails_5.1.x.gemfile
  - gemfiles/Rails_5.2.x.gemfile
  - gemfiles/Rails_6.0.x.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    on_success: never
    on_failure: always
