language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails-4.0-stable
  - gemfiles/Gemfile-rails-4.1-stable
  - gemfiles/Gemfile-rails-4.2-stable
  - gemfiles/Gemfile-rails-5.0-stable
  - gemfiles/Gemfile-rails-5.1-stable
  - gemfiles/Gemfile-rails-4.0
  - gemfiles/Gemfile-rails-4.1
  - gemfiles/Gemfile-rails-4.2
  - gemfiles/Gemfile-rails-5.0
  - gemfiles/Gemfile-rails-5.1

env:
  - ISOLATED=true

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile-rails-5.0
      env: ISOLATED=true
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile-rails-5.0-stable
      env: ISOLATED=true
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile-rails-5.1
      env: ISOLATED=true
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile-rails-5.1-stable
      env: ISOLATED=true
    - rvm: 2.0
      gemfile: gemfiles/gemfile-rails-5.0
      env: ISOLATED=true
    - rvm: 2.0
      gemfile: gemfiles/gemfile-rails-5.0-stable
      env: ISOLATED=true
    - rvm: 2.0
      gemfile: gemfiles/gemfile-rails-5.1
      env: ISOLATED=true
    - rvm: 2.0
      gemfile: gemfiles/gemfile-rails-5.1-stable
      env: ISOLATED=true
    - rvm: 2.1
      gemfile: gemfiles/gemfile-rails-5.0
      env: ISOLATED=true
    - rvm: 2.1
      gemfile: gemfiles/gemfile-rails-5.0-stable
      env: ISOLATED=true
    - rvm: 2.1
      gemfile: gemfiles/gemfile-rails-5.1
      env: ISOLATED=true
    - rvm: 2.1
      gemfile: gemfiles/gemfile-rails-5.1-stable
      env: ISOLATED=true

  allow_failures:
    - rvm: ruby-head

notifications:
  email: false
