language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
gemfile:
  - gemfiles/Gemfile-rails-4.0-stable
  - gemfiles/Gemfile-rails-4.1-stable
  - gemfiles/Gemfile-rails-4.2-stable
  - gemfiles/Gemfile-rails-5.0-stable
  - gemfiles/Gemfile-rails-4.0
  - gemfiles/Gemfile-rails-4.1
  - gemfiles/Gemfile-rails-4.2
  - gemfiles/Gemfile-rails-5.0

notifications:
  email: false
