language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

gemfile:
  - gemfiles/Rails_5.0.x
  - gemfiles/Rails_5.1.x
  - gemfiles/Rails_5.2.x

matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/Rails_master

notifications:
  email: false
