language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails-5.0-stable
  - gemfiles/Gemfile-rails-5.1-stable
  - gemfiles/Gemfile-rails-5.0
  - gemfiles/Gemfile-rails-5.1

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email: false
